# Generated by Django 4.0.5 on 2022-10-06 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_jogo', models.CharField(max_length=200, verbose_name='Jogo:')),
                ('estilo_do_jogo', models.CharField(choices=[('Ação', 'Ação'), ('Aventura', 'Aventura'), ('Corrida', 'Corrida'), ('Futebol', 'Futebol'), ('MMORPG', 'MMORPG'), ('Outros', 'Outros')], default='Outros', max_length=50, verbose_name='Estilo:')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='jogos', verbose_name='Imagem:')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['nome_do_jogo'],
            },
        ),
    ]
