# Generated by Django 4.0.5 on 2022-12-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='estoque',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='nome_do_jogo',
            field=models.CharField(error_messages={'unique': 'Já existe um jogo com este nome.'}, max_length=200, unique=True),
        ),
    ]
