# Generated by Django 4.1 on 2022-08-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='estilo_do_jogo',
            field=models.CharField(max_length=50),
        ),
    ]
