# Generated by Django 4.1 on 2022-08-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jogos', '0004_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
    ]
