# Generated by Django 4.1 on 2022-08-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogos', '0005_remove_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil', verbose_name='Imagem:'),
        ),
    ]
