# Generated by Django 4.0.5 on 2022-12-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogos', '0007_alter_jogos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
